package com.mywuwu.quartz.entity;

import java.util.Date;

public class Quartz {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartztask.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartztask.jobName
     *
     * @mbggenerated
     */
    private String jobname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartztask.triggerName
     *
     * @mbggenerated
     */
    private String triggername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartztask.groupName
     *
     * @mbggenerated
     */
    private String groupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartztask.className
     *
     * @mbggenerated
     */
    private String classname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartztask.createDateTime
     *
     * @mbggenerated
     */
    private Date createdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartztask.createUaerName
     *
     * @mbggenerated
     */
    private String createuaername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartztask.updateDateTime
     *
     * @mbggenerated
     */
    private Date updatedatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartztask.updateUserName
     *
     * @mbggenerated
     */
    private String updateusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartztask.cron
     *
     * @mbggenerated
     */
    private String cron;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartztask.id
     *
     * @return the value of quartztask.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartztask.id
     *
     * @param id the value for quartztask.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartztask.jobName
     *
     * @return the value of quartztask.jobName
     *
     * @mbggenerated
     */
    public String getJobname() {
        return jobname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartztask.jobName
     *
     * @param jobname the value for quartztask.jobName
     *
     * @mbggenerated
     */
    public void setJobname(String jobname) {
        this.jobname = jobname == null ? null : jobname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartztask.triggerName
     *
     * @return the value of quartztask.triggerName
     *
     * @mbggenerated
     */
    public String getTriggername() {
        return triggername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartztask.triggerName
     *
     * @param triggername the value for quartztask.triggerName
     *
     * @mbggenerated
     */
    public void setTriggername(String triggername) {
        this.triggername = triggername == null ? null : triggername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartztask.groupName
     *
     * @return the value of quartztask.groupName
     *
     * @mbggenerated
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartztask.groupName
     *
     * @param groupname the value for quartztask.groupName
     *
     * @mbggenerated
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartztask.className
     *
     * @return the value of quartztask.className
     *
     * @mbggenerated
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartztask.className
     *
     * @param classname the value for quartztask.className
     *
     * @mbggenerated
     */
    public void setClassname(String classname) {
        this.classname = classname == null ? null : classname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartztask.createDateTime
     *
     * @return the value of quartztask.createDateTime
     *
     * @mbggenerated
     */
    public Date getCreatedatetime() {
        return createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartztask.createDateTime
     *
     * @param createdatetime the value for quartztask.createDateTime
     *
     * @mbggenerated
     */
    public void setCreatedatetime(Date createdatetime) {
        this.createdatetime = createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartztask.createUaerName
     *
     * @return the value of quartztask.createUaerName
     *
     * @mbggenerated
     */
    public String getCreateuaername() {
        return createuaername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartztask.createUaerName
     *
     * @param createuaername the value for quartztask.createUaerName
     *
     * @mbggenerated
     */
    public void setCreateuaername(String createuaername) {
        this.createuaername = createuaername == null ? null : createuaername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartztask.updateDateTime
     *
     * @return the value of quartztask.updateDateTime
     *
     * @mbggenerated
     */
    public Date getUpdatedatetime() {
        return updatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartztask.updateDateTime
     *
     * @param updatedatetime the value for quartztask.updateDateTime
     *
     * @mbggenerated
     */
    public void setUpdatedatetime(Date updatedatetime) {
        this.updatedatetime = updatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartztask.updateUserName
     *
     * @return the value of quartztask.updateUserName
     *
     * @mbggenerated
     */
    public String getUpdateusername() {
        return updateusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartztask.updateUserName
     *
     * @param updateusername the value for quartztask.updateUserName
     *
     * @mbggenerated
     */
    public void setUpdateusername(String updateusername) {
        this.updateusername = updateusername == null ? null : updateusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartztask.cron
     *
     * @return the value of quartztask.cron
     *
     * @mbggenerated
     */
    public String getCron() {
        return cron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartztask.cron
     *
     * @param cron the value for quartztask.cron
     *
     * @mbggenerated
     */
    public void setCron(String cron) {
        this.cron = cron == null ? null : cron.trim();
    }
}